In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame([[1,2,3,4,5,6],[2,3,4,5,6,7,9]])

In [16]:


df = pd.DataFrame({
    "Name": ["MANISH","ROHAN","SHASHTRI"],
    "CLASS": ["B.TECH","M.TECH","PHD"],
    "SUB": ["SCIENCE","HUMAN LANGUAGE","LODA LEHSUN"],
})

df.dtypes

Name     object
CLASS    object
SUB      object
dtype: object

In [17]:
df = pd.read_csv("students_dataset.csv")
df.head()

,Name,Gender,StudyTime,ParentalEducation,LunchType,TestPreparation,MathScore,ReadingScore,WritingScore
0,Aarav Sharma,male,2.5,high_school,standard,none,65,60,62.0
1,Ananya Verma,female,3.0,bachelor,free,reduced,78,82,80.0
2,Rohan Singh,male,1.5,associate,standard,none,55,58,54.0
3,Priya Gupta,female,2.8,master,standard,completed,88,90,92.0
4,Karan Mehta,male,3.2,bachelor,free,none,72,70,68.0

In [18]:
df["Avg Score"] = df[["MathScore","ReadingScore","WritingScore"]].mean(axis=1)

In [19]:
df.head()

,Name,Gender,StudyTime,ParentalEducation,LunchType,TestPreparation,MathScore,ReadingScore,WritingScore,Avg Score
0,Aarav Sharma,male,2.5,high_school,standard,none,65,60,62.0,62.333333
1,Ananya Verma,female,3.0,bachelor,free,reduced,78,82,80.0,80.000000
2,Rohan Singh,male,1.5,associate,standard,none,55,58,54.0,55.666667
3,Priya Gupta,female,2.8,master,standard,completed,88,90,92.0,90.000000
4,Karan Mehta,male,3.2,bachelor,free,none,72,70,68.0,70.000000

In [20]:
df.isnull().head()

,Name,Gender,StudyTime,ParentalEducation,LunchType,TestPreparation,MathScore,ReadingScore,WritingScore,Avg Score
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False

In [21]:
df.isnull().sum()

Name                 0
Gender               0
StudyTime            0
ParentalEducation    0
LunchType            0
TestPreparation      0
MathScore            0
ReadingScore         0
WritingScore         1
Avg Score            0
dtype: int64