## About Dataset

### Context

This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

### Content

5-core dataset of product reviews from Amazon Kindle Store category from **May 1996 - July 2014**.

Contains a total of **982,619 entries**.

Each reviewer has at least **5 reviews** and each product has at least **5 reviews** in this dataset.

### Columns

- **asin** - ID of the product, like `B000FA64PK`
- **helpful** - Helpfulness rating of the review, example: `2/3`
- **overall** - Rating of the product
- **reviewText** - Text of the review
- **reviewTime** - Time of the review (raw)
- **reviewerID** - ID of the reviewer, like `A3SPTOKDG7WBLN`
- **reviewerName** - Name of the reviewer
- **summary** - Summary of the review
- **unixReviewTime** - Unix timestamp

### Acknowledgements

This dataset is taken from Amazon product data by **Julian McAuley, UCSD**.

### Inspiration

- Sentiment analysis on reviews
- Understanding how people rate usefulness of a review
- Understanding what factors influence the helpfulness of a review
- Fake reviews / outliers
- Best rated product IDs
- Similarity between products based on reviews
- Any other interesting analysis

### ```Best Practices```

1. **Preprocessing and Cleaning**
2. **Train-Test Split**
3. **Feature Extraction**
   - BOW (Bag of Words)
   - TF-IDF
   - Word2Vec
4. **Train ML Algorithms**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
import pandas as pd

df = pd.read_csv("all_kindle_review.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [4]:
from IPython.display import display
import pandas as pd

print('='*60)
print('📊 EXPLORATORY DATA ANALYSIS (EDA) SUMMARY')
print('='*60)

print('\n📌 Dataset Shape')
print(df.shape)

print('\n📌 First 5 Rows')
display(df.head())

print('\n📌 Last 5 Rows')
display(df.tail())

print('\n📌 Random Sample')
display(df.sample(5))

print('\n📌 Column Names')
display(pd.DataFrame(df.columns, columns=['Columns']))

print('\n📌 Data Types')
display(df.dtypes.to_frame('Data Type'))

print('\n📌 Dataset Information')
df.info()

print('\n📌 Missing Values')
display(df.isnull().sum().to_frame('Missing Values'))

print('\n📌 Duplicate Rows')
print(df.duplicated().sum())

print('\n📌 Numerical Summary')
display(df.describe().T)

print('\n📌 Categorical Summary')
display(df.describe(include='object').T)

print('\n📌 Correlation Matrix')
display(df.corr(numeric_only=True))

print('\n✅ EDA Completed Successfully!')

============================================================
📊 EXPLORATORY DATA ANALYSIS (EDA) SUMMARY
============================================================

📌 Dataset Shape
(12000, 11)

📌 First 5 Rows

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

📌 Last 5 Rows

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
11995,11995,2183,B001DUGORO,"[0, 0]",4,Valentine cupid is a vampire- Jena and Ian ano...,"02 28, 2014",A1OKS5Q1HD8WQC,lisa jon jung,jena,1393545600
11996,11996,6272,B002JCSFSQ,"[2, 2]",5,I have read all seven books in this series. Ap...,"05 16, 2011",AQRSPXLNEQAMA,TerryLP,Peacekeepers Series,1305504000
11997,11997,12483,B0035N1V7K,"[0, 1]",3,This book really just wasn't my cuppa. The si...,"07 26, 2013",A2T5QLT5VXOJAK,hwilson,a little creepy,1374796800
11998,11998,3640,B001W1XT40,"[1, 2]",1,"tried to use it to charge my kindle, it didn't...","09 17, 2013",A28MHD2DDY6DXB,"Allison A. Slater ""Gryphon50""",didn't work,1379376000
11999,11999,11398,B003370JUS,"[5, 6]",3,Taking Instruction is a look into the often hi...,"07 5, 2012",A3JUXLB4K9ZXCC,Dafna Yee,"If you like BDSM with a touch of romance, this...",1341446400

📌 Random Sample

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
6985,6985,2236,B001ECQK8O,"[0, 0]",5,If you're looking for a cutesy book about kitt...,"08 1, 2013",A2145U91X7BLS,fran,Sisypuss,1375315200
10762,10762,3078,B001T4YZ16,"[0, 0]",5,This book was so good I couldn't put it down I...,"10 17, 2013",A1BQO66R6OLCCW,Amazon Customer,Wow,1381968000
841,841,23646,B003Y3BP36,"[0, 3]",1,Just don't bother...even at free it's not wort...,"12 8, 2011",A1RT9W39NFZT8,Nicole,Not even for free....,1323302400
2818,2818,1350,B0015Z7VWE,"[1, 2]",5,I'm totally in love with Lila Dubois and her M...,"07 23, 2011",A28DYCKH8ZCWCJ,Liz,So hot my kindle caught fire!,1311379200
3116,3116,1919,B001BXNQ2O,"[0, 0]",5,"This was a good twist, on a already great stor...","07 1, 2012",A1U28SQHYF2MST,Anya Alsobrook,OMG... So good!,1341100800

📌 Column Names

           Columns
0     Unnamed: 0.1
1       Unnamed: 0
2             asin
3          helpful
4           rating
5       reviewText
6       reviewTime
7       reviewerID
8     reviewerName
9          summary
10  unixReviewTime

📌 Data Types

               Data Type
Unnamed: 0.1       int64
Unnamed: 0         int64
asin              object
helpful           object
rating             int64
reviewText        object
reviewTime        object
reviewerID        object
reviewerName      object
summary           object
unixReviewTime     int64

📌 Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    12000 non-null  int64
 1   Unnamed: 0      12000 non-null  int64
 2   asin            12000 non-null  object
 3   helpful         12000 non-null  object
 4   rating          12000 non-null  int64
 5   reviewText      12000 non-null  object
 6   reviewTime      12000 non-null  object
 7   reviewerID      12000 non-null  object
 8   reviewerName    11962 non-null  object
 9   summary         11998 non-null  object
 10  unixReviewTime  12000 non-null  int64
dtypes: int64(4), object(7)
memory usage: 1.0+ MB

📌 Missing Values

                Missing Values
Unnamed: 0.1                 0
Unnamed: 0                   0
asin                         0
helpful                      0
rating                       0
reviewText                   0
reviewTime                   0
reviewerID                   0
reviewerName                38
summary                      2
unixReviewTime               0

📌 Duplicate Rows
0

📌 Numerical Summary

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0.1,12000.0,5.999500e+03,3.464246e+03,0.0,2.999750e+03,5.999500e+03,8.999250e+03,1.199900e+04
Unnamed: 0,12000.0,1.002428e+04,1.050223e+04,0.0,2.999750e+03,5.999500e+03,1.247575e+04,4.777000e+04
rating,12000.0,3.250000e+00,1.421619e+00,1.0,2.000000e+00,3.500000e+00,4.250000e+00,5.000000e+00
unixReviewTime,12000.0,1.344537e+09,4.369374e+07,960249600.0,1.316218e+09,1.356826e+09,1.376870e+09,1.405814e+09

📌 Categorical Summary

,count,unique,top,freq
asin,12000,2114,B002AJ7X2C,111
helpful,12000,393,"[0, 0]",5690
reviewText,12000,12000,"Jace Rankin may be short, but he's nothing to ...",1
reviewTime,12000,1953,"02 18, 2013",37
reviewerID,12000,7614,A320TMDV6KCFU,125
reviewerName,11962,6735,Amazon Customer,659
summary,11998,10126,Good,41

📌 Correlation Matrix

                Unnamed: 0.1  Unnamed: 0    rating  unixReviewTime
Unnamed: 0.1        1.000000    0.000195 -0.006458       -0.009740
Unnamed: 0          0.000195    1.000000 -0.688832        0.072668
rating             -0.006458   -0.688832  1.000000       -0.029778
unixReviewTime     -0.009740    0.072668 -0.029778        1.000000

✅ EDA Completed Successfully!