## About Dataset

### Context

This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

### Content

5-core dataset of product reviews from Amazon Kindle Store category from **May 1996 - July 2014**.

Contains a total of **982,619 entries**.

Each reviewer has at least **5 reviews** and each product has at least **5 reviews** in this dataset.

### Columns

- **asin** - ID of the product, like `B000FA64PK`
- **helpful** - Helpfulness rating of the review, example: `2/3`
- **overall** - Rating of the product
- **reviewText** - Text of the review
- **reviewTime** - Time of the review (raw)
- **reviewerID** - ID of the reviewer, like `A3SPTOKDG7WBLN`
- **reviewerName** - Name of the reviewer
- **summary** - Summary of the review
- **unixReviewTime** - Unix timestamp

### Acknowledgements

This dataset is taken from Amazon product data by **Julian McAuley, UCSD**.

### Inspiration

- Sentiment analysis on reviews
- Understanding how people rate usefulness of a review
- Understanding what factors influence the helpfulness of a review
- Fake reviews / outliers
- Best rated product IDs
- Similarity between products based on reviews
- Any other interesting analysis

### ```Best Practices```

1. **Preprocessing and Cleaning**
2. **Train-Test Split**
3. **Feature Extraction**
   - BOW (Bag of Words)
   - TF-IDF
   - Word2Vec
4. **Train ML Algorithms**

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [31]:
import pandas as pd

df = pd.read_csv("all_kindle_review.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [32]:
from IPython.display import display
import pandas as pd

print('='*60)
print('📊 EXPLORATORY DATA ANALYSIS (EDA) SUMMARY')
print('='*60)

print('\n📌 Dataset Shape')
print(df.shape)

print('\n📌 First 5 Rows')
display(df.head())

print('\n📌 Last 5 Rows')
display(df.tail())

print('\n📌 Random Sample')
display(df.sample(5))

print('\n📌 Column Names')
display(pd.DataFrame(df.columns, columns=['Columns']))

print('\n📌 Data Types')
display(df.dtypes.to_frame('Data Type'))

print('\n📌 Dataset Information')
df.info()

print('\n📌 Missing Values')
display(df.isnull().sum().to_frame('Missing Values'))

print('\n📌 Duplicate Rows')
print(df.duplicated().sum())

print('\n📌 Numerical Summary')
display(df.describe().T)

print('\n📌 Categorical Summary')
display(df.describe(include='object').T)

print('\n📌 Correlation Matrix')
display(df.corr(numeric_only=True))

print('\n✅ EDA Completed Successfully!')

============================================================
📊 EXPLORATORY DATA ANALYSIS (EDA) SUMMARY
============================================================

📌 Dataset Shape
(12000, 11)

📌 First 5 Rows

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

📌 Last 5 Rows

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
11995,11995,2183,B001DUGORO,"[0, 0]",4,Valentine cupid is a vampire- Jena and Ian ano...,"02 28, 2014",A1OKS5Q1HD8WQC,lisa jon jung,jena,1393545600
11996,11996,6272,B002JCSFSQ,"[2, 2]",5,I have read all seven books in this series. Ap...,"05 16, 2011",AQRSPXLNEQAMA,TerryLP,Peacekeepers Series,1305504000
11997,11997,12483,B0035N1V7K,"[0, 1]",3,This book really just wasn't my cuppa. The si...,"07 26, 2013",A2T5QLT5VXOJAK,hwilson,a little creepy,1374796800
11998,11998,3640,B001W1XT40,"[1, 2]",1,"tried to use it to charge my kindle, it didn't...","09 17, 2013",A28MHD2DDY6DXB,"Allison A. Slater ""Gryphon50""",didn't work,1379376000
11999,11999,11398,B003370JUS,"[5, 6]",3,Taking Instruction is a look into the often hi...,"07 5, 2012",A3JUXLB4K9ZXCC,Dafna Yee,"If you like BDSM with a touch of romance, this...",1341446400

📌 Random Sample

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
5523,5523,25448,B0040JHR8K,"[1, 2]",1,It's not really an entire story. It's more lik...,"12 28, 2011",A3KBSZYDH3DA18,Amazon Customer,You got to pay for the sequel,1325030400
11959,11959,4183,B0028K2T54,"[0, 0]",4,"Not the deepest materiaI, but think this autho...","07 24, 2013",A2S7FA0XHW3K8T,archeopteryx,kinda cute,1374624000
5916,5916,3278,B001V5JCTI,"[1, 1]",1,This book started out very Slow with absolutel...,"08 2, 2013",A24M2A9VVMPR4D,Love Christian Romance,Avid Reader,1375401600
6765,6765,4062,B00273BHC8,"[0, 1]",2,I didn't enjoy this story. It was so drawn ou...,"07 29, 2011",AXCAQORZA8BGL,"Emerson Eureka ""True Reviewer""",So disappointing!,1311897600
8719,8719,3575,B001VLXML6,"[1, 2]",3,"I ""bought"" this quickly and didn't realize it ...","06 1, 2011",AF3L7C0YNE516,Kindle Customer,Abridged version of a story,1306886400

📌 Column Names

           Columns
0     Unnamed: 0.1
1       Unnamed: 0
2             asin
3          helpful
4           rating
5       reviewText
6       reviewTime
7       reviewerID
8     reviewerName
9          summary
10  unixReviewTime

📌 Data Types

               Data Type
Unnamed: 0.1       int64
Unnamed: 0         int64
asin              object
helpful           object
rating             int64
reviewText        object
reviewTime        object
reviewerID        object
reviewerName      object
summary           object
unixReviewTime     int64

📌 Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    12000 non-null  int64
 1   Unnamed: 0      12000 non-null  int64
 2   asin            12000 non-null  object
 3   helpful         12000 non-null  object
 4   rating          12000 non-null  int64
 5   reviewText      12000 non-null  object
 6   reviewTime      12000 non-null  object
 7   reviewerID      12000 non-null  object
 8   reviewerName    11962 non-null  object
 9   summary         11998 non-null  object
 10  unixReviewTime  12000 non-null  int64
dtypes: int64(4), object(7)
memory usage: 1.0+ MB

📌 Missing Values

                Missing Values
Unnamed: 0.1                 0
Unnamed: 0                   0
asin                         0
helpful                      0
rating                       0
reviewText                   0
reviewTime                   0
reviewerID                   0
reviewerName                38
summary                      2
unixReviewTime               0

📌 Duplicate Rows
0

📌 Numerical Summary

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0.1,12000.0,5.999500e+03,3.464246e+03,0.0,2.999750e+03,5.999500e+03,8.999250e+03,1.199900e+04
Unnamed: 0,12000.0,1.002428e+04,1.050223e+04,0.0,2.999750e+03,5.999500e+03,1.247575e+04,4.777000e+04
rating,12000.0,3.250000e+00,1.421619e+00,1.0,2.000000e+00,3.500000e+00,4.250000e+00,5.000000e+00
unixReviewTime,12000.0,1.344537e+09,4.369374e+07,960249600.0,1.316218e+09,1.356826e+09,1.376870e+09,1.405814e+09

📌 Categorical Summary

,count,unique,top,freq
asin,12000,2114,B002AJ7X2C,111
helpful,12000,393,"[0, 0]",5690
reviewText,12000,12000,"Jace Rankin may be short, but he's nothing to ...",1
reviewTime,12000,1953,"02 18, 2013",37
reviewerID,12000,7614,A320TMDV6KCFU,125
reviewerName,11962,6735,Amazon Customer,659
summary,11998,10126,Good,41

📌 Correlation Matrix

                Unnamed: 0.1  Unnamed: 0    rating  unixReviewTime
Unnamed: 0.1        1.000000    0.000195 -0.006458       -0.009740
Unnamed: 0          0.000195    1.000000 -0.688832        0.072668
rating             -0.006458   -0.688832  1.000000       -0.029778
unixReviewTime     -0.009740    0.072668 -0.029778        1.000000

✅ EDA Completed Successfully!

In [33]:
df = df[['reviewText','rating']]
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [34]:
df.shape

(12000, 2)

In [35]:
## missing value
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [36]:
from IPython.display import display
import pandas as pd

print('='*60)
print('📊 EXPLORATORY DATA ANALYSIS (EDA) SUMMARY')
print('='*60)

print('\n📌 Dataset Shape')
print(df.shape)

print('\n📌 First 5 Rows')
display(df.head())

print('\n📌 Last 5 Rows')
display(df.tail())

print('\n📌 Random Sample')
display(df.sample(5))

print('\n📌 Column Names')
display(pd.DataFrame(df.columns, columns=['Columns']))

print('\n📌 Data Types')
display(df.dtypes.to_frame('Data Type'))

print('\n📌 Dataset Information')
df.info()

print('\n📌 Missing Values')
display(df.isnull().sum().to_frame('Missing Values'))

print('\n📌 Duplicate Rows')
print(df.duplicated().sum())

print('\n📌 Numerical Summary')
display(df.describe().T)

print('\n📌 Categorical Summary')
display(df.describe(include='object').T)

print('\n📌 Correlation Matrix')
display(df.corr(numeric_only=True))

print('\n✅ EDA Completed Successfully!')

============================================================
📊 EXPLORATORY DATA ANALYSIS (EDA) SUMMARY
============================================================

📌 Dataset Shape
(12000, 2)

📌 First 5 Rows

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

📌 Last 5 Rows

                                              reviewText  rating
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

📌 Random Sample

                                             reviewText  rating
1310  So my rating is not necessarily Ms. Hewson's f...       2
2670  The main character of this book has no focus e...       1
9411  It started so well then fizzled out...*** ther...       2
9914  I was very disappointed with the master of kin...       3
4504  Stay with me was worth its price. But you must...       4

📌 Column Names

      Columns
0  reviewText
1      rating

📌 Data Types

           Data Type
reviewText    object
rating         int64

📌 Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   reviewText  12000 non-null  object
 1   rating      12000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 187.6+ KB

📌 Missing Values

            Missing Values
reviewText               0
rating                   0

📌 Duplicate Rows
0

📌 Numerical Summary

          count  mean       std  min  25%  50%   75%  max
rating  12000.0  3.25  1.421619  1.0  2.0  3.5  4.25  5.0

📌 Categorical Summary

,count,unique,top,freq
reviewText,12000,12000,"Jace Rankin may be short, but he's nothing to ...",1

📌 Correlation Matrix

        rating
rating     1.0

✅ EDA Completed Successfully!

In [37]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [38]:
## preprocessing and Cleaning

In [40]:
## postive review is 1 and neg is 0
df['rating'] = df['rating'].apply(lambda x:0 if x<3 else 1)

In [41]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [42]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [46]:
## 1. Lower All th cases
df['reviewText']=df['reviewText'].str.lower()

In [47]:
df.head()

                                          reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [48]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DEV_MANISH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [49]:
from bs4 import BeautifulSoup

In [52]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

In [57]:
df.head()

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [60]:
## apply word net Lemmatizer

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [61]:
def lemmatize_word(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [62]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_word(x))

In [63]:
df.head()

                                          reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [64]:
## train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['reviewText'],df['rating'] ,test_size=0.2, random_state=42
)

#### ``` part to of video has started```

In [69]:
## aplly bag of words

from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer()

X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [70]:

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = CountVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [71]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(9600, 35726))

In [73]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf,y_train)

In [74]:
# BOW Prediction
y_pred_bow = nb_model_bow.predict(X_test_bow)

# TF-IDF Prediction
y_pred_tfidf = nb_model_tfidf.predict(X_test_tfidf)

In [75]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# BOW
print("BOW")
print(confusion_matrix(y_test, y_pred_bow))
print(accuracy_score(y_test, y_pred_bow))
print(classification_report(y_test, y_pred_bow))


# TF-IDF
print("\nTF-IDF")
print(confusion_matrix(y_test, y_pred_tfidf))
print(accuracy_score(y_test, y_pred_tfidf))
print(classification_report(y_test, y_pred_tfidf))

BOW
[[499 304]
 [717 880]]
0.5745833333333333
              precision    recall  f1-score   support

           0       0.41      0.62      0.49       803
           1       0.74      0.55      0.63      1597

    accuracy                           0.57      2400
   macro avg       0.58      0.59      0.56      2400
weighted avg       0.63      0.57      0.59      2400


TF-IDF
[[499 304]
 [717 880]]
0.5745833333333333
              precision    recall  f1-score   support

           0       0.41      0.62      0.49       803
           1       0.74      0.55      0.63      1597

    accuracy                           0.57      2400
   macro avg       0.58      0.59      0.56      2400
weighted avg       0.63      0.57      0.59      2400